env:
  browser: true
  es6: true
  node: true

extends:
  - plugin:@typescript-eslint/recommended
  - google

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2021
  sourceType: module

plugins:
  - "@typescript-eslint"

rules:
  "@typescript-eslint/no-unused-vars":
    - error

  "@typescript-eslint/no-empty-interface":
    - error

  indent:
    - error
    - 2
    - MemberExpression: 1

  max-len:
    - error
    - code: 120

  no-unused-vars:
    - off
